# Generated by Django 5.0 on 2023-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
